version: 2.1

jobs:
  build_android:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build Android
          command: |
            cd android
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release-apks

workflows:
  version: 2
  build:
    jobs:
      - build_android
