version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0  # Node.js version
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}  # Cache dependencies based on lock file
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
